version: '3.7'

volumes:
  another_postgres_data:

networks:
  elk-network:
    driver: bridge

services:
  db-product:
    image: postgres:16
    container_name: db-product
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - another_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - elk-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-network
