spring:
  application:
    name: product-server

  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory #redis in hibernates api's used
          redisson:
            config: src/main/resources/redisson.yml
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgresql
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

  cache:
    type: redis
    redis:
      time-to-live: 6000000
      cache-null-values: false
management:
  endpoint:
    health:
      show-details: always

server:
  port: 8081







